name: E2E tests - Playwright
on: [pull_request]

jobs:
  playwright-tests:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        GRAFANA_VERSION: ['latest', '10.1.5', '10.0.6', '9.5.0', '9.1.5', '9.0.5', '8.5.5']
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v3

      - name: Copy auth file
        run: mkdir playwright && mkdir -p playwright/.auth && cp .github/workflows/scripts/user.json playwright/.auth/user.json

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install yarn dependencies
        run: yarn install
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Build frontend
        run: yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start Grafana
        run: docker run --rm -d -p 3001:3000 --name=grafana --env AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} --env AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_KEY }} --env GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-redshift-datasource,grafana-clock-panel --env GF_INSTALL_PLUGINS=grafana-redshift-datasource,grafana-clock-panel grafana/grafana:${{ matrix.GRAFANA_VERSION }}; sleep 30

      - name: Run Playwright tests
        run: yarn playwright:test
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-${{ matrix.GRAFANA_VERSION }}
          path: playwright-report/
          retention-days: 30
